config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"
  get "about", to: "pages#about", as: "page_about"
  resources :paks do
    resources :bookings, only:[:show, :new, :create]
  end
  resources :bookings
  resources :users
  resources :paks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pak
  # validates :date_debut, :date_fin, presence: true
end

app/models/pak.rb
class Pak < ApplicationRecord
  has_many :user
  has_many :booking
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :paks
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
# require "Date"

class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show]
  before_action :set_pak, only: %i[:create, :new]

  def index
    # affiche la derniere commande du client
    @lastUserBooking = Booking.find(params[:format])

  end

  def show
    @booking = Booking.new
  end

  def new
    @pak = Pak.find(params[:pak_id])
    @bookings = Booking.new
  end

  def create
    @pak = Pak.find(params[:pak_id])
    @booking = Booking.new(booking_params)

    @booking.user = current_user
    @booking.pak = @pak
    # @booking.created_at = Date.today
    # @booking.updated_at = Date.today

    if @booking.save!
      # raise
      # redirect_to paks_path
      redirect_to bookings_path(@booking)
    else
      raise
    end

  end

  def edit
    @booking = Booking.new
  end

  def update
    booking.save
  end

  def destroy
    @booking.destroy
    redirect_to pak_path(@booking), status: :see_other
  end

  private
  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at)
  end

  def set_pak
    @pak = Pak.find(params[:pak_id])
    raise
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # comment
  def index
  end

  def about
  end
end

app/controllers/pak.rb
class Pak < ApplicationRecord
  has_many :user_id
  has_one_attached :photo
end

app/controllers/paks_controller.rb
class PaksController < ApplicationController
  before_action :set_pak_id, only: %i[show edit update destroy]
  def index
    @paks = Pak.all
  end

  def show
    @pak = Pak.find(params[:id])
    @booking = Booking.new
  end

  def new
    @pak = Pak.new
  end

  def create
    @pak = Pak.new(pak_params)
    @pak.save!
    redirect_to pak_path(@pak)
  end

  def update
    @pak.update(pak_params)
    redirect_to pak_path(@pak)
  end

  def destroy
    @pak.destroy
    redirect_to paks_path
  end

  def search
    @pak = Pak.find(params[:id])
  end

  def edit

  end

private

  def pak_params
    params.require(:pak).permit(:name,:owner_name, :description, :pricing, :photo)
  end

  def set_pak_id
    @pak = Pak.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to users_path
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :address, :phone, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/paks_helper.rb
module PaksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/create.html.erb
<h1>Booking#create</h1>
<p>Find me in app/views/booking/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Booking#destroy</h1>
<p>Find me in app/views/booking/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Booking#edit</h1>
<p>Find me in app/views/booking/edit.html.erb</p>

app/views/bookings/index.html.erb
 <div class="container py-5  ">
  <h1 class="fw-bold text-decoration-underline"><a href="/" class="text-decoration-none text-dark"><i class="fa-sharp fa-solid fa-house"></i></a>Votre réservation</h1>

  <div class="d-flex  ">

      <!--Première colonne -->
      <div class="col-6">
          <div class="book-intro">
          <p>
            Exellent choix !<br>
            Nous vous remerçions pour votre réservation
          </p>
          <p>
              <i class="fa-solid fa-thumbs-up fs-2 me-5 "></i>
          </p>
      </div>

      <div class="book-resa mt-4">
          <h2>Détails de la réservation</h2>
          <div class="resume-resa d-flex">
              <div>
                <p><strong>Date de début</strong></p>
                <p><%= @lastUserBooking.starts_at.strftime("%a, %d %b %Y")%></p>
              </div>

              <div>
                <p><strong>Date de fin</strong></p>
                <p><%= @lastUserBooking.ends_at.strftime("%a, %d %b %Y")%></p>
              </div>
          </div>
          <hr style="width:500px">
      </div>
    </div>

    <!--Seconde colonne -->
    <div class="col-6">
        <div class="resum-tarif d-flex  ">
            <%= cl_image_tag(@lastUserBooking.pak.photo.key, width: 100, height: 100  , crop: :fill, :class => "sho-img") %>
            <p><%=@lastUserBooking.pak.name%><br>
                <%=@lastUserBooking.pak.description%>
            </p>
        </div>
        <div class="div-paiement"><a href="/" class="btn-paiement"> Payer la commande</a></div>




    </div>

  </div>
<!--fin des deux colonne-->
</div>

<div class="container">
    <h2>Choisissez comment vous souhaitez payer</h2>
    <div class="select-paiement">
        <p><strong>Payez la totalité</strong><br>Payez le total maintenant et vous aurez terminé.</p>
        <p>
          <strong><%= @lastUserBooking.pak.pricing %> € </strong>
          <input type="radio">
        </p>
    </div>

    <div class="select-paiement">
        <p><strong>Payez une partie maintenant et l'autre plus tard</strong><br>
        Payez <%= @lastUserBooking.pak.pricing / 2%> € maintenant et le solde (<%= @lastUserBooking.pak.pricing / 2%> €)<br>sera prélevé automatiquement via le même mode de paiement le 13 mars 2023. Aucuns frais supplémentaires.</p>
        <p>
          <strong><%= @lastUserBooking.pak.pricing / 2   %> € </strong>
          <input type="radio">
        </p>
    </div>

</div>

app/views/bookings/new.html.erb
<h1>Booking#new</h1>
<%= simple_form_for(@booking) do |f| %>
  <%= f.input :user_id %>
  <%= f.input :pak_id %>
  <%= f.input :starts_at %>
  <%= f.input :ends_at %>
  <%= f.submit %>
<% end %>
<p>Find me in app/views/booking/new.html.erb</p>

app/views/bookings/show.html.erb
<h1>Booking#show</h1>
<p>Find me in app/views/booking/show.html.erb</p>

app/views/bookings/update.html.erb
<h1>Booking#update</h1>
<p>Find me in app/views/booking/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Locabetes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render "shared/footer"%>
  </body>


</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/pages/about.html.erb
<h2>About Us!</h2>
<div class="container mt-5" style="background-image: url('<%= cl_image_path "https://res.cloudinary.com/dz6lwhhko/image/upload/v1668536185/development/boeuf_qdvs3g.jpg", height: 300, crop: :fill %>'); background-position: center top; background-repeat: no-repeat; padding-top: 300px">
    <h3 style="text-align: center;">Welcome To <span id="W_Name1">locabetes</span></h3>
    <p><span id="W_Name2">locabetes</span> is a Professional <span id="W_Type1">eCommerce</span> Platform. Here we will provide you only interesting content, which you will like very much. We're dedicated to providing you the best of <span id="W_Type2">eCommerce</span>, with a focus on dependability and <span id="W_Spec">Booking</span>. We're working to turn our passion for <span id="W_Type3">eCommerce</span> into a booming <a href="https://www.blogearns.com/2021/05/free-about-us-page-generator.html" rel="do-follow" style="color: inherit; text-decoration: none;">online website</a>. We hope you enjoy our <span id="W_Type4">eCommerce</span> as much as we enjoy offering them to you.</p>
    <p>I will keep posting more important posts on my Website for all of you. Please give your support and love.</p>
    <p style="font-weight: bold; text-align: center;">Thanks For Visiting Our Site<br><br>
    <span style="color: blue; font-size: 16px; font-weight: bold; text-align: center;">Have a nice day!</span></p>
</div>

app/views/pages/index.html.erb
<div class="container">
  <%= render "shared/banner"%>
  <%= render "shared/card_products"%>

  <div class="cta">
    <div class="">
      <h2 class="">Unleash your Genius</h2>
      <p class="">Your data's glamorous new life begins today.</p>
    </div>
    <a href="/paks" target="_blank" class="btn btn-primary btn-lg">Get started with Locabête</a>
  </div>
</div>

app/views/paks/_form.html.erb
    <%= simple_form_for(@pak) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :pricing %>
      <%= f.input :photo, as: :file %>
      <%= f.submit %>
    <% end %>

app/views/paks/create.html.erb
<h1>Paks#create</h1>
<p>Find me in app/views/paks/create.html.erb</p>
<%= render "form" %>

app/views/paks/delete.html.erb
<h1>Paks#delete</h1>
<p>Find me in app/views/paks/delete.html.erb</p>

app/views/paks/edit.html.erb
<h1>Paks#edit</h1>
<p>Find me in app/views/paks/edit.html.erb</p>
<%= render "form" %>

app/views/paks/index.html.erb
<%# <%= render "shared/card_paks" %>
<%= render "shared/barre_de_recherche" %>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle m-4 " type="button" data-bs-toggle="dropdown" aria-expanded="false"> Option</button>

  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="<%= new_pak_path(@paks) %>">Créé un nouveau pack</a></li>
  </ul>

  <div class="container">
    <div class = "row ">
      <% @paks.each do |pak| %>
        <div class="col-4 ">
          <%= link_to pak do %>
            <div class="card1 mb-4 ">
              <%= cl_image_tag pak.photo.key, height: 300, width: 400, crop: :fill %>
                <div class="card-infos1">
                  <div >
                    <h2 class="text-body text-decoration-none "><%= pak.name %> </h2><br>
                    <p class="text-body text-decoration-none"> <%= pak.description %></p>
                  </div>
                  <p style="font-size: 16px!important;" id="no-underline" class="card-pricing1 text-body"><h3><%= pak.pricing %>€</h3> </p>
                </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <!-- <%= render "shared/card_paks" %>-->
</div>

<section class="section-home-hero">
  <div class="container"></div>
</section>

<section class="section-home-features">
  <div class="container"></div>
</section>

<section class="section-home-cta">
  <div class="container"></div>
</section>

<section class="section-home-cta">
  <div class="container"></div>
</section>

app/views/paks/new.html.erb
<%= render "form" %>
<p><%= link_to "retourné a l'accueil", paks_path %></p>

app/views/paks/search.html.erb
<h1>Paks#search</h1>
<p>Find me in app/views/paks/search.html.erb</p>

app/views/paks/show.html.erb
<div class="container py-5  ">
  <h1 class="fw-bold text-decoration-underline"><%= link_to "<", paks_path, :class => "text-decoration-none text-dark" %>    <%= @pak.name %></h1>

  <div class="carte-mere d-flex justify-content-between">
      <div class="zone-img">
          <%= cl_image_tag @pak.photo.key, height: 450, width: 500, crop: :fill, :class => "img-show" %>
      </div>

      <div class="reservation">

          <div class="d-flex align-items-center">
              <p class="fs-2"><strong><%= @pak.pricing %> €</strong> <%= @pak.duration %> </p>

              <p class="show-rating ms-5"><i class="fa-solid fa-star"></i> <%= @pak.rating %></p>
          </div>

          <!-- selection des dates de location -->
          <div class="show-date">
              <%= simple_form_for [@pak, @booking] do |f| %>
                <div class="d-flex justify-content-around mt-3">
                    <div><%= f.input :starts_at, label: "Début de location", as: :date, html5: true, required: true, :input_html => { :class => 'fdate' } %></div>
                   <div><%= f.input :ends_at, label: "Fin de location", as: :date, html5: true, required: true, :input_html => { :class => 'ldate' } %></div>
                </div>
                <div class="d-flex justify-content-center mb-3" data-controller="show-btn">
                    <%= f.submit "réserver maintenant",  :class => "show-btn btn btn-primary", 'data-action': "click->show-btn#clicBtn" %>
                </div>
              <% end %>
          </div>
          <div>
            <hr>
              <p><%= @pak.description%></p>
          </div>
    </div>

  </div>

  <p class="mt-5">
    <strong class="fs-3"><span class="show-color">Locabêtes</span>Cover</strong><br>
    Chaque réservation comprend une protection gratuite en cas d'annulation par l'hôte, d'inexactitudes dans la description du logement, ainsi que d'autres problèmes comme les difficultés d'accès au logement.
    En savoir plus
  </p>
</div>




 <!--<p><%= link_to "Retourné a l'accueil", paks_path %></p>
<%= link_to paks_path(@pak), method: :delete, data: { confirm: "Are you sure?" } do %>
delete
<% end %>-->

app/views/paks/update.html.erb
<h1>Paks#update</h1>
<p>Find me in app/views/paks/update.html.erb</p>

<%= render "shared/card_paks" %>
<p><%= link_to "retourné a l'accueil", paks_path %></p>

app/views/shared/_banner.html.erb
<div class="home-banner">
    <div class="banner-text">
        <h1>Locabêtes<br>972</h1>
        <p>Lorem ipsum dolor sit amet. Non aliquam incidunt et quod quia non quisquam placeat hic veritatis delectus</p>
        <a href="/paks" class="btn btn-primary">Voir les produits</a>
    </div>

    <div class="banner-img">
        <%= image_tag("https://res.cloudinary.com/dz6lwhhko/image/upload/v1668568690/development/banniere2_axwerm.jpg", width: 400, height: 550, crop: :fill) %>
    </div>
</div>

<img class="hero_img" src="https://images.unsplash.com/photo-1590249426516-4ac3a513c4cd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80" alt="">

<div class="hide">
  <h1 class="display-4">Locabêtes<br>972</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Get started with Locabête</a>
  </p>
</div>

app/views/shared/_barre_de_recherche.html.erb
<div class = "container1">
  <div class="input-group rounded d-flex  mx-5 my-4">
    <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
    <span class="input-group-text border-0" id="search-addon">
      <i class="fas fa-search"></i>
    </span>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card1 col-6 col-md-4">
  <%= cl_image_tag @pak.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="card-infos1">
    <div>
      <h2><%= @pak.name %> </h2>
      <p> <%= @pak.description %></p>
    </div>
    <h2 class="card-pricing1"><%= @pak.pricing %> </h2>
  </div>
</div>
</div>

app/views/shared/_card_paks.html.erb
<div class = "row">
  <div class="col-sm-4">
    <% @paks.each do |pak| %>
       <div class="card1">
        <%= cl_image_tag pak.photo.key, height: 300, width: 400, crop: :fill %>
          <div class="card-infos1">
            <div>
              <h2><%= pak.name %> </h2>
              <p> <%= pak.description %></p>

            </div>
          <h2 class="card-pricing1"><%= pak.pricing %>€ </h2>
         <p> <%= link_to "aller sur l'article", pak%> </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_card_products.html.erb
<div class="cards_list">

    <div class="card-details-product">
        <img class="card_img" src="https://images.unsplash.com/photo-1628320563527-e7558b50e3f3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80" alt="Photo animal">
        <h2 class="card_title">Anes de Martinique</h2>
        <p>Lorem ipsum dolor sit amet. Et deserunt sunt aut minima cupiditate et velit harum vel laudantium ratione.</p>
        <div class="div-lien d-flex justify-content-center">
            <a href="#" class="btn btn-primary">Voir les produits</a>
        </div>
    </div>

    <div class="card-details-product">
        <img class="card_img" src="https://images.unsplash.com/photo-1598974357801-cbca100e65d3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80" alt="Photo animal">
        <h2 class="card_title">Chevaux de Martinique</h2>
        <p>Lorem ipsum dolor sit amet. Et deserunt sunt aut minima cupiditate et velit harum vel laudantium ratione.</p>
        <div class="div-lien d-flex justify-content-center">
            <a href="#" class="btn btn-primary">Voir les produits</a>
        </div>
    </div>

    <div class="card-details-product">
        <%= cl_image_tag("5d943d082eb93_img_0989_yk65id", crop: :fill, :class => "card_img") %>
        <h2 class="card_title">Moutons de Martinique</h2>
        <p>Lorem ipsum dolor sit amet. Et deserunt sunt aut minima cupiditate et velit harum vel laudantium ratione.</p>
        <div class="div-lien d-flex justify-content-center">
            <a href="#" class="btn btn-primary">Voir les produits</a>
        </div>
    </div>

    <div class="card-details-product">
        <%= cl_image_tag("5d943d082eb93_img_0989_yk65id", crop: :fill, :class => "card_img") %>
        <h2 class="card_title">Boeufs de Martinique</h2>
        <p>Lorem ipsum dolor sit amet. Et deserunt sunt aut minima cupiditate et velit harum vel laudantium ratione.</p>
        <div class="div-lien d-flex justify-content-center">
            <a href="#" class="btn btn-primary">Voir les produits</a>
        </div>
    </div>

    <div class="card-details-product">
        <%= cl_image_tag("5d943d082eb93_img_0989_yk65id", crop: :fill, :class => "card_img") %>
        <h2 class="card_title">Cabrits de Martinique</h2>
        <p>Lorem ipsum dolor sit amet. Et deserunt sunt aut minima cupiditate et velit harum vel laudantium ratione.</p>
        <div class="div-lien d-flex justify-content-center">
            <a href="#" class="btn btn-primary">Voir les produits</a>
        </div>
    </div>

</div>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="container">
        <div class="d-flex flex-row justify-content-between">
            <p class="footer_slogan col-4"><a href="https://www.youtube.com/watch?v=mReSNcDrWCA">Votre débroussailleuse 2.0 vous attend.</a></p>
            
            <ul class="footer_column d-flex flex-column">
              <li class="column_title">Explore</li>
              <li class="footer_item"><%= link_to "Accueil", root_path %></li>
              <li class="footer_item"><%= link_to "À propos", page_about_path %></li>
              <li class="footer_item"><%= link_to "Paks", paks_path %></li>
              <li class="footer_item"><a href="#">Jobs</a></li>
            </ul>
            <ul class="footer_column d-flex flex-column">
              <li class="column_title">Filtres</li>
              <li class="footer_item"><a href="#">Ânes</a></li>
              <li class="footer_item"><a href="#">Bœuf</a></li>
              <li class="footer_item"><a href="#">Cabrits</a></li>
              <li class="footer_item"><a href="#">Chevals</a></li>
              <li class="footer_item"><a href="#">Moutons</a></li>
            </ul>
            <ul class="footer_column d-flex flex-column">
              <li class="column_title">Ressources</li>
              <li class="footer_item"><a href="#">Communauté</a></li>
              <li class="footer_item"><a href="#">Tarifs</a></li>
              <li class="footer_item"><a href="#">Support</a></li>
            </ul>
        </div>
        <div class="footer_copyright d-flex flex-row justify-content-between">
            <ul class="social-wrapper col-6 d-flex flex-row">
                <li class="footer_item"><a href="#">Conditions d'utilisation</a></li>
                <li class="footer_item"><a href="#">Vie privée</a></li>
                <li class="footer_item"><a href="#">Contactez-nous</a></li>
                <li class="footer_item d-flex flex-row align-items-center">
                    <a href="#">Statut</a>
                    <% if user_signed_in? %>
                            <div class="bg-success"></div>
                        <% else %>
                            <div class="bg-danger"></div>
                        <% end %>
                </li>
            </ul>
            <ul class="footer_social-wrapper d-flex flex-row">
              <li class="footer_social-icon"><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
              <li class="footer_social-icon"><a href="https://github.com/MoulinBrice/locabetes"><i class="fa-brands fa-github"></i></a></li>
            </>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="nav">
    <div class="container">
        <div class="nav-wrapper d-flex flex-row justify-content-between">
            <%= link_to "/" do %>
                <img class="nav_logo" src="https://www.shutterstock.com/image-vector/goats-cartoon-character-chewing-grass-260nw-1896327754.jpg" alt="" srcset="">
            <% end %>

            <ul class="nav-action d-flex flex-row align-items-center">
                <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to "Accueil", "/" %></li>
                    <li class="nav-item"><%= link_to "Paks", "paks" %></li>
                    <li class="nav-item"><%= link_to "À propos", page_about_path %></li>
                    <li class="nav-item"><%#= link_to "Profil", user_path %></li>
                    <li class="nav-item dropdown">
                        <%= image_tag "https://images.unsplash.com/photo-1625019030820-e4ed970a6c95?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80", class: "nav_img", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navDropdown">
                            <%= link_to "Profil", "", class: "dropdown-item" %>
                            <%= link_to "Se déconnecter", "/", data: {turbo_method: :delete}, class: "dropdown-item" %>
                        </div>
                    </li>
                <% else %>
                    <li><%= link_to "Se connecter", new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/shared/_user_card.html.erb
<div class="container">

    <% @users.each do |user| %>
        <h1><%= user.first_name%> <%= user.last_name%></h1>
        <p><%= user.email%></p>
        <p><%= user.address%></p>
        <p><%= user.phone%></p>
    <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>
<p>hello</p>
<p>re</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div>
  <%= simple_form_for(@user) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :address %>
  <%= f.input :phone %>
  <%= f.input :email %>
  <%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>